num = range(10)
num = list(num)
print(num)
print('--------------------------------')
num = range(2,10)
num = list(num)
print(num)
print('--------------------------------')
num = range(2,10,2)
num = list(num)
print(num)
print('--------------------------------')
nu = range (10)
nu = list(nu)
for i in nu :
    print (i)
